// Code generated by protoc-gen-go (hand-written for MeshPulse).
// source: meshpulse.proto

package contract

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageSubmitMeasurement is submitted by a node to record a speed test on-chain.
type MessageSubmitMeasurement struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       []byte                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Ping          uint64                 `protobuf:"varint,2,opt,name=ping,proto3" json:"ping,omitempty"`
	Download      uint64                 `protobuf:"varint,3,opt,name=download,proto3" json:"download,omitempty"`
	Upload        uint64                 `protobuf:"varint,4,opt,name=upload,proto3" json:"upload,omitempty"`
	Isp           string                 `protobuf:"bytes,5,opt,name=isp,proto3" json:"isp,omitempty"`
	Region        string                 `protobuf:"bytes,6,opt,name=region,proto3" json:"region,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageSubmitMeasurement) Reset() {
	*x = MessageSubmitMeasurement{}
	mi := &file_meshpulse_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *MessageSubmitMeasurement) String() string {
	return protoimpl.X.MessageStringOf(x)
}
func (*MessageSubmitMeasurement) ProtoMessage() {}
func (x *MessageSubmitMeasurement) ProtoReflect() protoreflect.Message {
	mi := &file_meshpulse_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*MessageSubmitMeasurement) Descriptor() ([]byte, []int) {
	return file_meshpulse_proto_rawDescGZIP(), []int{0}
}
func (x *MessageSubmitMeasurement) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}
func (x *MessageSubmitMeasurement) GetPing() uint64 {
	if x != nil {
		return x.Ping
	}
	return 0
}
func (x *MessageSubmitMeasurement) GetDownload() uint64 {
	if x != nil {
		return x.Download
	}
	return 0
}
func (x *MessageSubmitMeasurement) GetUpload() uint64 {
	if x != nil {
		return x.Upload
	}
	return 0
}
func (x *MessageSubmitMeasurement) GetIsp() string {
	if x != nil {
		return x.Isp
	}
	return ""
}
func (x *MessageSubmitMeasurement) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

// MessageClaimReward allows a contributor to transfer earned $MESHP tokens.
type MessageClaimReward struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromAddress   []byte                 `protobuf:"bytes,1,opt,name=from_address,json=fromAddress,proto3" json:"fromAddress"`
	ToAddress     []byte                 `protobuf:"bytes,2,opt,name=to_address,json=toAddress,proto3" json:"toAddress"`
	Amount        uint64                 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageClaimReward) Reset() {
	*x = MessageClaimReward{}
	mi := &file_meshpulse_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}
func (x *MessageClaimReward) String() string {
	return protoimpl.X.MessageStringOf(x)
}
func (*MessageClaimReward) ProtoMessage() {}
func (x *MessageClaimReward) ProtoReflect() protoreflect.Message {
	mi := &file_meshpulse_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}
func (*MessageClaimReward) Descriptor() ([]byte, []int) {
	return file_meshpulse_proto_rawDescGZIP(), []int{1}
}
func (x *MessageClaimReward) GetFromAddress() []byte {
	if x != nil {
		return x.FromAddress
	}
	return nil
}
func (x *MessageClaimReward) GetToAddress() []byte {
	if x != nil {
		return x.ToAddress
	}
	return nil
}
func (x *MessageClaimReward) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

// ── Raw descriptor (generated from meshpulse.proto via protoc --descriptor_set_out) ──

var File_meshpulse_proto protoreflect.FileDescriptor

const file_meshpulse_proto_rawDesc = "\x0a\x0fmeshpulse.proto\x12\x05types\x22\xa6\x01\x0a\x18MessageSubmitMeasurement\x12\x18\x0a\x07address\x18\x01 \x01(\x0cR\x07address\x12\x12\x0a\x04ping\x18\x02 \x01(\x04R\x04ping\x12\x1a\x0a\x08download\x18\x03 \x01(\x04R\x08download\x12\x16\x0a\x06upload\x18\x04 \x01(\x04R\x06upload\x12\x10\x0a\x03isp\x18\x05 \x01(\x09R\x03isp\x12\x16\x0a\x06region\x18\x06 \x01(\x09R\x06region\x22n\x0a\x12MessageClaimReward\x12!\x0a\x0cfrom_address\x18\x01 \x01(\x0cR\x0bfromAddress\x12\x1d\x0a\x0ato_address\x18\x02 \x01(\x0cR\x09toAddress\x12\x16\x0a\x06amount\x18\x03 \x01(\x04R\x06amountB.Z,github.com/canopy-network/go-plugin/contractb\x06proto3"

var (
	file_meshpulse_proto_rawDescOnce sync.Once
	file_meshpulse_proto_rawDescData []byte
)

func file_meshpulse_proto_rawDescGZIP() []byte {
	file_meshpulse_proto_rawDescOnce.Do(func() {
		file_meshpulse_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meshpulse_proto_rawDesc), len(file_meshpulse_proto_rawDesc)))
	})
	return file_meshpulse_proto_rawDescData
}

var file_meshpulse_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_meshpulse_proto_goTypes = []any{
	(*MessageSubmitMeasurement)(nil), // 0: types.MessageSubmitMeasurement
	(*MessageClaimReward)(nil),       // 1: types.MessageClaimReward
}
var file_meshpulse_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_meshpulse_proto_init() }

func file_meshpulse_proto_init() {
	if File_meshpulse_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meshpulse_proto_rawDesc), len(file_meshpulse_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_meshpulse_proto_goTypes,
		DependencyIndexes: file_meshpulse_proto_depIdxs,
		MessageInfos:      file_meshpulse_proto_msgTypes,
	}.Build()
	File_meshpulse_proto = out.File
	file_meshpulse_proto_goTypes = nil
	file_meshpulse_proto_depIdxs = nil
}
